joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 3.0

    require_enable_button: true
    enable_button: 6  # low-right shoulder button
    enable_turbo_button: 5  # B- button
